-- GENERATED FILE — do not edit by hand.
--
-- Regenerate with:  npm run seed:generate
-- Source: lib/provinces.ts, lib/knowledge-base.ts, lib/resources.ts
--
-- Every statement is an upsert, so this is safe to re-apply to a populated
-- database. Referrals, cached answers and the verification log are untouched.
--
-- Note on resources: the verification verdict (verification, verify_note) is
-- PRESERVED on conflict. Once the legal desk confirms a number in the database,
-- re-running this seed will not revert it.

begin;

-- 7 provinces and territories
insert into provinces (id, name_en, name_ur, short_en, short_ur, min_marriage_age_female, min_marriage_age_female_status, has_vaw_centres, women_commission) values
  ('punjab', 'Punjab', 'پنجاب', 'Punjab', 'پنجاب', 16, 'confirmed', true, 'Punjab Commission on the Status of Women (PCSW)'),
  ('sindh', 'Sindh', 'سندھ', 'Sindh', 'سندھ', 18, 'confirmed', false, 'Sindh Commission on the Status of Women (SCSW)'),
  ('kp', 'Khyber Pakhtunkhwa', 'خیبر پختونخوا', 'KP', 'خیبر پختونخوا', 16, 'confirmed', false, 'Khyber Pakhtunkhwa Commission on the Status of Women'),
  ('balochistan', 'Balochistan', 'بلوچستان', 'Balochistan', 'بلوچستان', 16, 'confirmed', false, 'Balochistan Commission on the Status of Women'),
  ('ict', 'Islamabad Capital Territory', 'اسلام آباد وفاقی دارالحکومت', 'Islamabad', 'اسلام آباد', 18, 'unconfirmed', false, 'National Commission on the Status of Women (NCSW)'),
  ('gb', 'Gilgit-Baltistan', 'گلگت بلتستان', 'Gilgit-Baltistan', 'گلگت بلتستان', 16, 'unconfirmed', false, null),
  ('ajk', 'Azad Jammu & Kashmir', 'آزاد جموں و کشمیر', 'AJK', 'آزاد کشمیر', 16, 'unconfirmed', false, null)
on conflict (id) do update set
  name_en = excluded.name_en,
  name_ur = excluded.name_ur,
  short_en = excluded.short_en,
  short_ur = excluded.short_ur,
  min_marriage_age_female = excluded.min_marriage_age_female,
  min_marriage_age_female_status = excluded.min_marriage_age_female_status,
  has_vaw_centres = excluded.has_vaw_centres,
  women_commission = excluded.women_commission;

-- 29 legal instruments
insert into legal_instruments (id, title, short_title, jurisdiction, categories, protects, summary, remedy, confidence, published) values
  ('ppc_hurt', 'Pakistan Penal Code 1860, Sections 332–337 (Hurt)', 'PPC 332–337 (Hurt)', 'federal', '{"physical","domestic"}', null, 'Causing bodily pain, injury, disease or infirmity. Covers slapping, hitting, beating and wounding. Penalties scale with the severity and permanence of the injury.', 'Register an FIR at the police station with jurisdiction over where the incident happened. A medico-legal certificate strengthens the case substantially.', 'confirmed', true),
  ('ppc_302', 'Pakistan Penal Code 1860, Section 302 (Qatl-i-amd)', 'PPC 302 (Murder)', 'federal', '{"physical","harmful_practice"}', null, 'Intentional killing, punishable by death or life imprisonment. Relevant where threats to life have been made.', null, 'confirmed', true),
  ('ppc_506', 'Pakistan Penal Code 1860, Section 506 (Criminal intimidation)', 'PPC 506 (Criminal intimidation)', 'federal', '{"physical","domestic","other"}', null, 'Threatening someone with injury to their person, reputation or property in order to alarm them or make them act against their will.', 'Report to police; threats in writing or recordings are strong evidence.', 'confirmed', true),
  ('peca_2016', 'Prevention of Electronic Crimes Act 2016', 'PECA 2016', 'federal', '{"cyber","sexual"}', null, 'Section 20 covers offences against a person''s dignity; Section 21 covers sharing sexually explicit content without consent (5–7 years and fine up to PKR 5 million); Section 24 covers cyber stalking.', 'Complain to the cyber crime authority in person or online. Preserve every screenshot, URL and profile before blocking anyone.', 'confirmed', true),
  ('workplace_harassment_2010', 'Protection against Harassment of Women at the Workplace Act 2010 (as amended 2022)', 'Workplace Harassment Act 2010 (am. 2022)', 'federal', '{"workplace","sexual"}', null, 'Covers unwelcome sexual advances, demands for sexual favours in exchange for work benefits, and conduct creating a hostile working environment. The 2022 amendment widened the definition of workplace and employee to include students, domestic workers, home-based and informal workers, and gig workers.', 'File with your organisation''s Inquiry Committee within 30 days, or go directly to the Ombudsperson if the organisation has no committee. Appeals go to the Ombudsperson within 30 days of a decision.', 'confirmed', true),
  ('transgender_2018', 'Transgender Persons (Protection of Rights) Act 2018', 'Transgender Persons Act 2018', 'federal', '{"physical","sexual","workplace","economic","other"}', '{"transgender"}', 'Guarantees the right to self-perceived gender identity, inheritance, education, employment, healthcare and access to public spaces. Harassment of a transgender person carries 6 months to 3 years imprisonment and a fine up to PKR 100,000.', 'Complaints can be pursued through the police and through the National Commission for Human Rights.', 'confirmed', true),
  ('honour_2016', 'Criminal Law (Amendment) (Offences in the name or pretext of Honour) Act 2016', 'Anti-Honour Killing Act 2016', 'federal', '{"harmful_practice","physical"}', null, 'Removed the forgiveness loophole that previously let families pardon a killer under Qisas and Diyat. Honour killings now carry a mandatory life sentence of at least 25 years, and the death penalty remains available.', null, 'confirmed', true),
  ('anti_women_practices_2011', 'Prevention of Anti-Women Practices (Criminal Law Amendment) Act 2011', 'Anti-Women Practices Act 2011', 'federal', '{"harmful_practice","economic","family_law"}', '{"woman"}', 'Criminalises giving a woman in marriage to settle a dispute (vani or swara), forced marriage, marriage to the Quran, and depriving a woman of her inheritance. Penalties run 3 to 10 years.', null, 'confirmed', true),
  ('ppc_354', 'Pakistan Penal Code 1860, Section 354', 'PPC 354 (Assault to outrage modesty)', 'federal', '{"sexual"}', '{"woman"}', 'Assault or criminal force against a woman intending to outrage her modesty. Up to 2 years imprisonment and a fine.', null, 'confirmed', true),
  ('ppc_509', 'Pakistan Penal Code 1860, Section 509', 'PPC 509 (Insulting modesty / harassment)', 'federal', '{"sexual","workplace"}', '{"woman"}', 'Words, gestures or acts intended to insult the modesty of a woman, including sexual harassment. Up to 3 years and a fine.', null, 'confirmed', true),
  ('ppc_375_376', 'Pakistan Penal Code 1860, Sections 375–376 (Rape)', 'PPC 375–376 (Rape)', 'federal', '{"sexual"}', null, 'Rape carries death or 10 to 25 years imprisonment; gang rape carries death or life imprisonment. The Anti-Rape (Investigation and Trial) Act 2021 added special courts and protections for the survivor''s identity.', 'A medico-legal examination should be sought as early as possible, at a government hospital. Do not wash or change clothes beforehand if that can be avoided.', 'confirmed', true),
  ('ppc_498a', 'Pakistan Penal Code 1860, Section 498-A', 'PPC 498-A (Depriving a woman of inheritance)', 'federal', '{"economic","family_law"}', '{"woman"}', 'Depriving a woman of her inheritance by deceitful or illegal means. Inserted by the Prevention of Anti-Women Practices Act 2011 and punishable by 5 to 10 years or a fine of PKR 1 million, or both.', null, 'confirmed', true),
  ('ppc_498b', 'Pakistan Penal Code 1860, Section 498-B', 'PPC 498-B (Forced marriage)', 'federal', '{"harmful_practice","family_law"}', '{"woman"}', 'Compelling a woman to marry against her will. Punishable by 3 to 10 years and a fine of PKR 500,000.', null, 'confirmed', true),
  ('ppc_310a', 'Pakistan Penal Code 1860, Section 310-A', 'PPC 310-A (Badl-i-sulh, vani, swara)', 'federal', '{"harmful_practice","family_law"}', '{"woman"}', 'Giving a woman or girl in marriage to settle a civil dispute or criminal liability. 3 to 10 years imprisonment.', null, 'confirmed', true),
  ('ppc_365b', 'Pakistan Penal Code 1860, Section 365-B', 'PPC 365-B (Abduction to compel marriage)', 'federal', '{"harmful_practice","sexual"}', '{"woman"}', 'Kidnapping or abducting a woman in order to compel her to marry, or to force or seduce her into illicit intercourse. Life imprisonment or 10 to 25 years.', null, 'confirmed', true),
  ('mfl_1961', 'Muslim Family Laws Ordinance 1961', 'Muslim Family Laws Ordinance 1961', 'federal', '{"family_law"}', null, 'Governs registration of marriage, talaq procedure, polygamy permissions through the Arbitration Council, dower (mehr) and maintenance obligations.', null, 'confirmed', true),
  ('dmma_1939', 'Dissolution of Muslim Marriages Act 1939', 'Dissolution of Muslim Marriages Act 1939', 'federal', '{"family_law"}', '{"woman"}', 'Sets out the grounds on which a Muslim woman may obtain a decree dissolving her marriage, including cruelty, failure to maintain, and desertion. Khula is available through the Family Court and does not require the husband''s consent.', 'File in the Family Court of your district. The nikah nama is the essential document.', 'confirmed', true),
  ('guardians_wards_1890', 'Guardians and Wards Act 1890', 'Guardians and Wards Act 1890', 'federal', '{"family_law","child"}', null, 'The overarching custody and guardianship statute. Courts decide custody on the welfare of the child, which overrides the default hizanat age rules where the child''s safety is at stake.', null, 'confirmed', true),
  ('family_courts_1964', '(West Pakistan) Family Courts Act 1964', 'Family Courts Act 1964', 'federal', '{"family_law"}', null, 'Establishes the Family Courts that hear dissolution of marriage, dower, maintenance, custody and guardianship, and recovery of dowry articles. Adopted with local amendments in each province.', null, 'confirmed', true),
  ('womens_property_2020', 'Enforcement of Women''s Property Rights Act 2020', 'Women''s Property Rights Act 2020', 'ict', '{"economic","family_law"}', '{"woman"}', 'A woman deprived of property she owns or inherited can complain to the Ombudsman, who can order restoration of possession, transfer of title, police assistance and compensation for lost rent. Decisions are targeted within 60 days.', null, 'confirmed', true),
  ('dv_ict_2012', 'Domestic Violence (Prevention and Protection) Act 2012', 'DV Act 2012 (Islamabad)', 'ict', '{"domestic","physical","economic"}', null, 'Applies in the Islamabad Capital Territory. Covers physical, sexual, psychological and economic abuse within a domestic relationship and is gender-neutral, so it protects men and transgender household members too.', 'Apply to the Court of Magistrate for a protection order, residence order or monetary relief.', 'confirmed', true),
  ('dv_punjab_2016', 'Punjab Protection of Women against Violence Act 2016', 'Punjab PWVA 2016', 'punjab', '{"domestic","physical","economic","sexual"}', '{"woman"}', 'Covers physical, sexual, psychological and economic abuse and stalking against women in Punjab. Establishes Violence Against Women Centres and the 1043 helpline, and provides for protection, residence and monetary orders.', 'Apply to the Family Court, or go to a Violence Against Women Centre, which combines police reporting, medical examination, prosecution and shelter in one building.', 'confirmed', true),
  ('dv_sindh_2013', 'Sindh Domestic Violence (Prevention and Protection) Act 2013', 'Sindh DV Act 2013', 'sindh', '{"domestic","physical","economic"}', null, 'Sindh''s own domestic violence statute. Covers physical, sexual, psychological and economic abuse in a domestic relationship, and provides for protection, residence and monetary orders.', 'Apply to the Court of Judicial Magistrate for a protection order.', 'confirmed', true),
  ('dv_balochistan_2014', 'Balochistan Domestic Violence (Prevention and Protection) Act 2014', 'Balochistan DV Act 2014', 'balochistan', '{"domestic","physical","economic"}', null, 'Balochistan''s domestic violence statute, providing for protection orders, residence orders and monetary relief for abuse within a domestic relationship.', null, 'confirmed', true),
  ('dv_kp_2021', 'Khyber Pakhtunkhwa Domestic Violence against Women (Prevention and Protection) Act 2021', 'KP DV Act 2021', 'kp', '{"domestic","physical","economic"}', '{"woman"}', 'Khyber Pakhtunkhwa''s domestic violence statute, replacing reliance on federal provisions. Provides for protection orders and relief for women subjected to abuse in a domestic relationship.', null, 'confirmed', true),
  ('child_marriage_sindh_2013', 'Sindh Child Marriages Restraint Act 2013', 'Sindh Child Marriages Restraint Act 2013', 'sindh', '{"child","harmful_practice","family_law"}', null, 'Sets the minimum age of marriage at 18 for both parties in Sindh, making it the strictest such law in the country. Contracting, conducting or facilitating a child marriage is a cognisable offence.', null, 'confirmed', true),
  ('child_marriage_1929', 'Child Marriage Restraint Act 1929', 'Child Marriage Restraint Act 1929', 'federal', '{"child","harmful_practice","family_law"}', null, 'The default position outside Sindh and Islamabad: the minimum age of marriage is 16 for a female and 18 for a male. Punjab increased the penalties in 2015 without changing the age.', null, 'confirmed', true),
  ('ghag_kp_2013', 'Khyber Pakhtunkhwa Elimination of the Custom of Ghag Act 2013', 'KP Ghag Act 2013', 'kp', '{"harmful_practice","family_law"}', '{"woman"}', 'Criminalises ghag, the custom of a man publicly claiming a woman for marriage to prevent anyone else from proposing. Carries imprisonment of 3 to 7 years and a fine.', null, 'confirmed', true),
  ('property_kp_2019', 'Khyber Pakhtunkhwa Enforcement of Women''s Property Rights Act 2019', 'KP Women''s Property Rights Act 2019', 'kp', '{"economic","family_law"}', '{"woman"}', 'Allows a woman deprived of her property or inheritance in Khyber Pakhtunkhwa to complain to the provincial Ombudsperson for restoration of her rights.', null, 'confirmed', true)
on conflict (id) do update set
  title = excluded.title,
  short_title = excluded.short_title,
  jurisdiction = excluded.jurisdiction,
  categories = excluded.categories,
  protects = excluded.protects,
  summary = excluded.summary,
  remedy = excluded.remedy,
  confidence = excluded.confidence,
  published = excluded.published;

-- 6 NCSW categories
insert into ncsw_categories (id, name, name_ur, description, legal_refs, case_categories, sort_order) values
  ('physical', 'Physical Violence', null, 'Acts of physical aggression that cause or could cause physical harm, pain, injury, or death.', '{"Pakistan Penal Code Sections 332-337 (Hurt)","Punjab Protection of Women against Violence Act 2016, Section 2(o)(1)","Domestic Violence (Prevention and Protection) Act 2012"}', '{"physical","domestic"}', 0),
  ('sexual', 'Sexual Violence', null, 'Any sexual act, attempt, or unwanted sexual contact or comments directed against a woman using coercion, force, or threats.', '{"PPC Sections 354, 354-A, 375-376, 509","Protection of Women (Criminal Laws Amendment) Act 2006","Punjab Protection of Women against Violence Act 2016"}', '{"sexual"}', 1),
  ('psychological', 'Psychological / Emotional Violence', null, 'Acts causing mental or emotional suffering, including psychological deterioration resulting from oppressive behaviour.', '{"Punjab Protection of Women against Violence Act 2016, Section 2(o)(2)","Domestic Violence (Prevention and Protection) Act 2012"}', '{"domestic","other"}', 2),
  ('harmful_traditional', 'Harmful Traditional Practices', null, 'Customary practices harmful to women, often justified by culture or community norms. Recognised as violence under Pakistani law.', '{"Prevention of Anti-Women Practices (Criminal Law Amendment) Act 2011","Criminal Law (Amendment) (Offences in the name or pretext of Honour) Act 2016","Child Marriage Restraint Act 1929 (amended)"}', '{"harmful_practice","family_law"}', 3),
  ('economic', 'Economic Violence', null, 'Controlling financial resources, preventing work, denying maintenance, or exploiting labour.', '{"Punjab Protection of Women against Violence Act 2016","Domestic Violence (Prevention and Protection) Act 2012","Prevention of Anti-Women Practices Act 2011 (inheritance)"}', '{"economic","domestic"}', 4),
  ('cyber', 'Cyber Violence / Technology-Facilitated VAW', null, 'Online harassment, blackmail, non-consensual image sharing, digital stalking. Added as a Pakistan-specific category during stakeholder consultations.', '{"Prevention of Electronic Crimes Act (PECA) 2016","Punjab Protection of Women against Violence Act 2016 (includes cyber crime)"}', '{"cyber"}', 5)
on conflict (id) do update set
  name = excluded.name,
  name_ur = excluded.name_ur,
  description = excluded.description,
  legal_refs = excluded.legal_refs,
  case_categories = excluded.case_categories,
  sort_order = excluded.sort_order;

-- 41 NCSW indicators
insert into ncsw_indicators (id, category_id, indicator, indicator_ur, description, severity, examples, legal_ref_extra, published, sort_order) values
  ('phys_01', 'physical', 'Hitting, slapping, kicking, punching, or beating', null, 'Any act of striking with hands, fists, feet, or body parts', 'serious', '{"Husband slaps wife during argument","In-law beats daughter-in-law","Brother hits sister for going out"}', null, true, 0),
  ('phys_02', 'physical', 'Pushing, shoving, pulling hair, dragging', null, 'Physical force used to control, intimidate, or cause pain', 'serious', '{"Partner shoves woman against wall","Father drags daughter by hair"}', null, true, 1),
  ('phys_03', 'physical', 'Throwing objects at a woman', null, 'Using projectiles — dishes, shoes, furniture, phones', 'serious', '{"Husband throws plate during dinner","Objects thrown during argument"}', null, true, 2),
  ('phys_04', 'physical', 'Burning, scalding, or acid attacks', null, 'Use of fire, hot liquids, acid, or corrosive substances', 'critical', '{"Acid thrown on face","Stove burning made to appear accidental"}', 'Acid Control and Acid Crime Prevention Act 2011', true, 3),
  ('phys_05', 'physical', 'Use of weapons — knife, firearm, stick, rod', null, 'Attacking or threatening with any weapon or instrument', 'critical', '{"Threatened with knife","Hit with rod or stick","Firearm used to threaten"}', null, true, 4),
  ('phys_06', 'physical', 'Choking, strangling, or suffocating', null, 'Restricting breathing or blood flow', 'critical', '{"Hands around throat during argument","Pillow held over face"}', null, true, 5),
  ('phys_07', 'physical', 'Confinement and restriction of movement', null, 'Locking in a room or space against her will', 'serious', '{"Locked in room to prevent leaving","Not allowed to leave house"}', null, true, 6),
  ('phys_08', 'physical', 'Murder or attempted murder (including honour killing)', null, 'Killing or attempting to kill, including in the name of so-called honour', 'critical', '{"Threats to kill for perceived dishonour","Family plotting harm for marriage choice"}', 'Criminal Law (Amendment) (Offences in the name or pretext of Honour) Act 2016', true, 7),
  ('sex_01', 'sexual', 'Rape and attempted rape', null, 'Forced intercourse or attempted forced intercourse without consent', 'critical', '{"Forced intercourse by stranger","Sexual assault by acquaintance"}', null, true, 0),
  ('sex_02', 'sexual', 'Marital rape / forced sexual acts by spouse', null, 'Sexual acts within marriage without consent. Recognised as violence by NCSW. Pakistan''s legal framework on marital rape is evolving.', 'critical', '{"Husband forces intercourse despite refusal","Coerced through threats"}', null, true, 1),
  ('sex_03', 'sexual', 'Unwanted touching, groping, grabbing', null, 'Non-consensual physical contact of a sexual nature', 'serious', '{"Groped in public transport","Unwanted touching by colleague"}', null, true, 2),
  ('sex_04', 'sexual', 'Verbal sexual harassment — comments, catcalling', null, 'Unwanted sexual remarks, explicit comments, degrading language', 'concerning', '{"Catcalling on the street","Sexual comments at workplace"}', null, true, 3),
  ('sex_05', 'sexual', 'Workplace sexual harassment', null, 'Unwanted sexual advances or hostile environment at work', 'serious', '{"Boss makes sexual advances","Promotion conditioned on sexual favours"}', 'Protection Against Harassment of Women at the Workplace Act 2010', true, 4),
  ('sex_06', 'sexual', 'Forced prostitution or sexual exploitation', null, 'Compelling into commercial sexual activity through force or coercion', 'critical', '{"Trafficked into sex work","Forced by family into prostitution"}', null, true, 5),
  ('sex_07', 'sexual', 'Sexual abuse of female children', null, 'Any sexual act or contact with a female minor', 'critical', '{"Child molestation","Sexual abuse by family member"}', 'Zainab Alert, Response and Recovery Act 2020', true, 6),
  ('psych_01', 'psychological', 'Verbal abuse — insults, humiliation, belittling', null, 'Repeated degrading language to undermine self-worth', 'concerning', '{"Called stupid or worthless regularly","Publicly humiliated","Constant criticism"}', null, true, 0),
  ('psych_02', 'psychological', 'Threats of violence, harm, or abandonment', null, 'Using threats to intimidate — threats to hit, kill, divorce, or take children', 'serious', '{"Threatens divorce if she visits parents","Threatens to take children","Threatens harm if she tells anyone"}', null, true, 1),
  ('psych_03', 'psychological', 'Controlling behaviour — isolation from family and friends', null, 'Restricting freedom of movement, social contact, or communication', 'serious', '{"Not allowed to visit parents","Phone taken away","Forbidden from having friends","Not allowed to work"}', null, true, 2),
  ('psych_04', 'psychological', 'Intimidation — destroying property, displaying weapons', null, 'Acts to frighten without direct physical contact', 'serious', '{"Smashes things during arguments","Punches walls near her"}', null, true, 3),
  ('psych_05', 'psychological', 'Stalking and surveillance', null, 'Repeated unwanted following, watching, monitoring', 'serious', '{"Ex follows her to work","Checks phone constantly","Shows up uninvited"}', null, true, 4),
  ('psych_06', 'psychological', 'Gaslighting — making victim doubt reality', null, 'Manipulating into questioning own memory or sanity', 'serious', '{"''That never happened, you''re imagining things''","''You''re crazy, no one will believe you''"}', null, true, 5),
  ('psych_07', 'psychological', 'Using children as tools of control', null, 'Threatening custody, turning children against mother', 'serious', '{"''I''ll take the kids''","Tells children their mother is bad"}', null, true, 6),
  ('trad_01', 'harmful_traditional', 'Honour killing (karo-kari) or threats', null, 'Murder or threat of murder in the name of so-called honour. Criminal offence.', 'critical', '{"Family threatens to kill for choosing own husband","Threats over social media use"}', null, true, 0),
  ('trad_02', 'harmful_traditional', 'Forced marriage', null, 'Compelling marriage without free and full consent', 'critical', '{"Parents arranging marriage without consent","Pressured through threats"}', null, true, 1),
  ('trad_03', 'harmful_traditional', 'Child / early marriage', null, 'Marriage of a girl under 16 (Sindh: 18). Criminal offence.', 'critical', '{"13-year-old being married off","Underage marriage arranged"}', null, true, 2),
  ('trad_04', 'harmful_traditional', 'Vani / Swara — women given to settle disputes', null, 'Giving a woman or girl to another family as compensation. Criminal offence.', 'critical', '{"Girl given to rival family to settle dispute","Jirga decides to exchange women"}', null, true, 3),
  ('trad_05', 'harmful_traditional', 'Watta-satta — exchange marriage', null, 'Reciprocal bride exchange where one marriage is conditional on another', 'concerning', '{"Marriage only agreed if brother also marries their daughter"}', null, true, 4),
  ('trad_06', 'harmful_traditional', 'Dowry-related violence', null, 'Violence or threats related to dowry demands', 'serious', '{"In-laws demanding more dowry","Beaten for insufficient dowry"}', null, true, 5),
  ('trad_07', 'harmful_traditional', 'Denial of inheritance rights', null, 'Depriving a woman of her legal right to inherit. Criminal offence.', 'serious', '{"Brothers take all land","Forced to sign away rights","Threatened for claiming inheritance"}', null, true, 6),
  ('trad_08', 'harmful_traditional', 'Forced conversion and marriage of minority women', null, 'Abducting, forcibly converting, and compelling marriage of religious minority women', 'critical', '{"Hindu girl kidnapped and forced to convert","Christian woman coerced"}', null, true, 7),
  ('econ_01', 'economic', 'Withholding financial resources or maintenance', null, 'Denying money for basic needs — food, healthcare, children', 'serious', '{"No money for household expenses","Has to beg for children''s school fees"}', null, true, 0),
  ('econ_02', 'economic', 'Controlling earnings or income', null, 'Taking salary, forcing handover of earnings, controlling bank account', 'serious', '{"Husband takes her salary","Not allowed own bank account"}', null, true, 1),
  ('econ_03', 'economic', 'Preventing from working', null, 'Forbidding employment, forcing to quit, sabotaging work', 'serious', '{"Husband forbids her from working","In-laws force her to quit"}', null, true, 2),
  ('econ_04', 'economic', 'Dispossession of property or assets', null, 'Taking, selling, or destroying personal property or assets', 'serious', '{"In-laws take gold jewellery","Property transferred without consent"}', null, true, 3),
  ('econ_05', 'economic', 'Denial of education', null, 'Preventing from attending school, college, or university', 'serious', '{"Pulled out of school","Not allowed to attend university"}', null, true, 4),
  ('cyber_01', 'cyber', 'Non-consensual sharing of intimate images or videos', null, 'Sharing or threatening to share private images without consent', 'critical', '{"Ex threatens to share private photos","Intimate photos posted without consent"}', null, true, 0),
  ('cyber_02', 'cyber', 'Online harassment and cyberbullying', null, 'Persistent online abuse, trolling, threats via social media or messaging', 'concerning', '{"Threatening WhatsApp messages","Abusive social media comments"}', null, true, 1),
  ('cyber_03', 'cyber', 'Digital blackmail or sextortion', null, 'Using private information or images to extort or coerce', 'critical', '{"Blackmailed with screenshots","Demanding money to not share photos"}', null, true, 2),
  ('cyber_04', 'cyber', 'Digital stalking and surveillance', null, 'Tracking location, monitoring messages, installing spyware, accessing accounts', 'serious', '{"Tracking app installed on phone","Someone logs into her accounts"}', null, true, 3),
  ('cyber_05', 'cyber', 'Impersonation and fake profiles', null, 'Creating fake profiles using a woman''s identity or photos to defame', 'serious', '{"Fake profile made with her photos","Someone impersonating her online"}', null, true, 4),
  ('cyber_06', 'cyber', 'Doxxing — publishing private information', null, 'Sharing personal info (address, phone, workplace) online to endanger', 'critical', '{"Home address posted with threats","Phone number shared to invite harassment"}', null, true, 5)
on conflict (id) do update set
  category_id = excluded.category_id,
  indicator = excluded.indicator,
  indicator_ur = excluded.indicator_ur,
  description = excluded.description,
  severity = excluded.severity,
  examples = excluded.examples,
  legal_ref_extra = excluded.legal_ref_extra,
  published = excluded.published,
  sort_order = excluded.sort_order;

-- 37 resources (10 confirmed)
insert into resources (id, name, name_ur, type, scope, phone, whatsapp, email, website, hours, hours_ur, description, description_ur, serves, handles, priority, verification, verify_note, published) values
  ('police_15', 'Police Emergency', 'پولیس ایمرجنسی', 'emergency', '{"national"}', '15', null, null, null, '24/7', 'ہر وقت', 'Nationwide police emergency line for immediate danger. You can also ask the police to escort you while you collect belongings from an unsafe home.', 'فوری خطرے کے لیے ملک بھر میں پولیس ایمرجنسی نمبر۔ آپ پولیس سے یہ بھی کہہ سکتی ہیں کہ وہ غیر محفوظ گھر سے آپ کا سامان لینے کے دوران آپ کے ساتھ جائیں۔', null, '{"physical","sexual","domestic","harmful_practice","other"}', 0, 'confirmed', null, true),
  ('rescue_1122', 'Rescue 1122', 'ریسکیو 1122', 'emergency', '{"punjab","kp"}', '1122', null, null, null, '24/7', 'ہر وقت', 'Emergency ambulance and rescue service. Call this for urgent medical help after an assault, including transport to a government hospital for a medico-legal examination.', 'ایمرجنسی ایمبولینس اور ریسکیو سروس۔ تشدد کے بعد فوری طبی مدد کے لیے کال کریں، بشمول میڈیکو لیگل معائنے کے لیے سرکاری ہسپتال تک منتقلی۔', null, '{"physical","sexual","domestic"}', 0, 'confirmed', null, true),
  ('mohr_1099', 'Ministry of Human Rights Helpline', 'وزارتِ انسانی حقوق ہیلپ لائن', 'government', '{"national"}', '1099', '0333-9085709', null, 'https://mohr.gov.pk/', 'Daytime, daily', 'روزانہ، دن کے اوقات میں', 'Free legal advice, counselling and referral on any human rights violation, anywhere in Pakistan. The most useful single number when you are not sure who else to call.', 'پاکستان میں کہیں بھی انسانی حقوق کی خلاف ورزی پر مفت قانونی مشورہ، کاؤنسلنگ اور رہنمائی۔ جب سمجھ نہ آئے کہ کس سے رابطہ کریں تو یہ سب سے مفید نمبر ہے۔', null, '{"domestic","physical","sexual","economic","family_law","harmful_practice","workplace","other"}', 1, 'confirmed', null, true),
  ('fia_cybercrime', 'FIA Cyber Crime Wing', 'ایف آئی اے سائبر کرائم ونگ', 'cyber', '{"national"}', '1991', null, null, 'https://complaint.fia.gov.pk/', '24/7 helpline; offices during working hours', 'ہیلپ لائن ہر وقت؛ دفاتر کام کے اوقات میں', 'Report online blackmail, sextortion, non-consensual sharing of private images, impersonation and cyber stalking. Complaints can be filed online or at a regional office. Preserve screenshots and URLs before you block anyone.', 'آن لائن بلیک میل، نجی تصاویر کا بغیر اجازت پھیلانا، جعلی اکاؤنٹ اور سائبر اسٹاکنگ کی شکایت درج کروائیں۔ شکایت آن لائن یا علاقائی دفتر میں کی جا سکتی ہے۔ کسی کو بلاک کرنے سے پہلے اسکرین شاٹس محفوظ کر لیں۔', null, '{"cyber","sexual"}', 1, 'confirmed', null, true),
  ('nccia', 'National Cyber Crime Investigation Agency (NCCIA)', 'نیشنل سائبر کرائم انویسٹی گیشن ایجنسی', 'cyber', '{"national"}', '1799', null, null, 'https://nccia.gov.pk/', 'Working hours', 'کام کے اوقات', 'The agency that has taken over cyber crime investigation from the FIA. Handles the same offences under PECA 2016.', 'وہ ادارہ جس نے ایف آئی اے سے سائبر کرائم کی تفتیش سنبھالی ہے۔ پیکا 2016 کے تحت وہی جرائم دیکھتا ہے۔', null, '{"cyber","sexual"}', 2, 'unconfirmed', 'Confirm the current public helpline number and whether complaints should now be routed to NCCIA rather than complaint.fia.gov.pk. The FIA-to-NCCIA transition means one of these two entries is likely to be stale.', true),
  ('fospah', 'Federal Ombudsperson for Protection against Harassment (FOSPAH)', 'وفاقی محتسب برائے انسدادِ ہراسانی', 'government', '{"national"}', null, null, null, 'https://www.fospah.gov.pk/', 'Working hours', 'کام کے اوقات', 'Decides workplace harassment complaints, and appeals from an employer''s inquiry committee. Since the 2022 amendment this covers students, domestic workers, home-based and gig workers, not only formal employees. Complaints can be filed online.', 'کام کی جگہ پر ہراسانی کی شکایات اور ادارے کی انکوائری کمیٹی کے فیصلوں کے خلاف اپیل سنتا ہے۔ 2022 کی ترمیم کے بعد اس میں طلبہ، گھریلو ملازمین اور غیر رسمی کارکن بھی شامل ہیں۔ شکایت آن لائن درج کی جا سکتی ہے۔', null, '{"workplace","sexual"}', 1, 'confirmed', 'Website confirmed. A public phone number should be added once verified.', true),
  ('fospah_punjab', 'Punjab Ombudsperson for Protection against Harassment', 'پنجاب محتسب برائے انسدادِ ہراسانی', 'government', '{"punjab"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Punjab''s own ombudsperson for workplace harassment complaints, and appeals from an employer''s inquiry committee. Closer than the federal office and usually faster.', 'کام کی جگہ پر ہراسانی کی شکایات اور ادارے کی انکوائری کمیٹی کے فیصلوں کے خلاف اپیل کے لیے پنجاب کا اپنا محتسب۔ وفاقی دفتر کی نسبت قریب اور عموماً تیز۔', null, '{"workplace","sexual"}', 1, 'unconfirmed', 'The office exists under the 2010 Act; confirm the current contact details and complaint intake route.', true),
  ('fospah_sindh', 'Sindh Ombudsperson for Protection against Harassment', 'سندھ محتسب برائے انسدادِ ہراسانی', 'government', '{"sindh"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Sindh''s ombudsperson for workplace harassment complaints and appeals against an inquiry committee''s decision.', 'کام کی جگہ پر ہراسانی کی شکایات اور انکوائری کمیٹی کے فیصلے کے خلاف اپیل کے لیے سندھ کا محتسب۔', null, '{"workplace","sexual"}', 1, 'unconfirmed', 'Confirm current contact details and complaint intake route.', true),
  ('fospah_kp', 'Khyber Pakhtunkhwa Ombudsperson for Protection against Harassment', 'خیبر پختونخوا محتسب برائے انسدادِ ہراسانی', 'government', '{"kp"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Khyber Pakhtunkhwa''s ombudsperson for workplace harassment complaints and appeals.', 'کام کی جگہ پر ہراسانی کی شکایات اور اپیلوں کے لیے خیبر پختونخوا کا محتسب۔', null, '{"workplace","sexual"}', 1, 'unconfirmed', 'Confirm current contact details and complaint intake route.', true),
  ('fospah_balochistan', 'Balochistan Ombudsperson for Protection against Harassment', 'بلوچستان محتسب برائے انسدادِ ہراسانی', 'government', '{"balochistan"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Balochistan''s ombudsperson for workplace harassment complaints and appeals.', 'کام کی جگہ پر ہراسانی کی شکایات اور اپیلوں کے لیے بلوچستان کا محتسب۔', null, '{"workplace","sexual"}', 1, 'unconfirmed', 'Confirm the office is operational, and its contact details.', true),
  ('nchr', 'National Commission for Human Rights (NCHR)', 'قومی کمیشن برائے انسانی حقوق', 'government', '{"national"}', '051-9217340', null, 'complaints@nchr.gov.pk', 'https://www.nchr.gov.pk/', 'Working hours', 'کام کے اوقات', 'Statutory body that receives and investigates human rights complaints, including where the police or a public authority have refused to act.', 'قانونی ادارہ جو انسانی حقوق کی شکایات وصول کرتا اور ان کی تحقیقات کرتا ہے، بشمول ان معاملات کے جہاں پولیس یا سرکاری ادارے نے کارروائی سے انکار کیا ہو۔', null, '{"physical","sexual","economic","harmful_practice","other"}', 3, 'unconfirmed', 'Confirm the direct complaints line and email are still current.', true),
  ('ncsw', 'National Commission on the Status of Women (NCSW)', 'قومی کمیشن برائے حیثیتِ نسواں', 'government', '{"national"}', null, null, null, 'https://www.ncsw.gov.pk/', 'Working hours', 'کام کے اوقات', 'The federal body overseeing women''s rights policy, and the source of the standardised indicators this app''s assessment is built on.', 'خواتین کے حقوق کی پالیسی کی نگرانی کرنے والا وفاقی ادارہ، اور ان معیاری اشاریوں کا ماخذ جن پر اس ایپ کا جائزہ مبنی ہے۔', '{"woman"}', '{"other"}', 4, 'confirmed', null, true),
  ('drf_cyber', 'Digital Rights Foundation — Cyber Harassment Helpline', 'ڈیجیٹل رائٹس فاؤنڈیشن — سائبر ہراسانی ہیلپ لائن', 'cyber', '{"national"}', '0800-39393', null, 'helpdesk@digitalrightsfoundation.pk', 'https://digitalrightsfoundation.pk/', 'Monday to Friday, working hours', 'پیر تا جمعہ، کام کے اوقات', 'Free, confidential helpline for online harassment. They walk you through evidence collection, platform takedown requests and the FIA complaint process, and offer legal and psychological support.', 'آن لائن ہراسانی کے لیے مفت، خفیہ ہیلپ لائن۔ وہ ثبوت جمع کرنے، مواد ہٹوانے اور ایف آئی اے میں شکایت کے عمل میں آپ کی رہنمائی کرتے ہیں، اور قانونی و نفسیاتی مدد فراہم کرتے ہیں۔', null, '{"cyber","sexual"}', 1, 'confirmed', null, true),
  ('madadgaar', 'Madadgaar National Helpline (LHRLA)', 'مددگار نیشنل ہیلپ لائن', 'ngo', '{"national"}', '1098', null, null, 'https://www.madadgaar.org/', 'Daytime', 'دن کے اوقات', 'Long-running national helpline run by Lawyers for Human Rights and Legal Aid, for women and children facing violence. Provides counselling, legal referral and shelter linkage.', 'تشدد کا سامنا کرنے والی خواتین اور بچوں کے لیے قومی ہیلپ لائن، جو لائرز فار ہیومن رائٹس اینڈ لیگل ایڈ چلاتی ہے۔ کاؤنسلنگ، قانونی رہنمائی اور شیلٹر تک رسائی فراہم کرتی ہے۔', '{"woman","child"}', '{"domestic","physical","sexual","child","family_law"}', 2, 'unconfirmed', '1098 is widely published for Madadgaar but should be dialled and confirmed, along with current operating hours.', true),
  ('darulaman_route', 'Dar-ul-Aman (government women''s shelter)', 'دارالامان (سرکاری خواتین شیلٹر)', 'shelter', '{"punjab","sindh","kp","balochistan","ict","gb","ajk"}', null, null, null, null, 'Admission 24/7 in most districts', 'زیادہ تر اضلاع میں داخلہ ہر وقت', 'State-run shelters for women in danger, present in most districts. There is no single national number: reach one through the 1099 helpline, the district Social Welfare Department, a Violence Against Women Centre, or by asking the Family Court for a shelter referral. A woman can be admitted without a male guardian''s permission.', 'خطرے میں گھری خواتین کے لیے سرکاری پناہ گاہیں، جو زیادہ تر اضلاع میں موجود ہیں۔ کوئی ایک قومی نمبر نہیں: 1099 ہیلپ لائن، ضلعی محکمہ سماجی بہبود، وی اے ڈبلیو سینٹر، یا فیملی کورٹ کے ذریعے رجوع کریں۔ خاتون کو کسی مرد سرپرست کی اجازت کے بغیر داخل کیا جا سکتا ہے۔', '{"woman","child"}', '{"domestic","physical","harmful_practice"}', 2, 'confirmed', 'Deliberately listed without a phone number because access is district-level. Consider adding per-district numbers for the highest-traffic cities.', true),
  ('legal_aid_society', 'Legal Aid Society', 'لیگل ایڈ سوسائٹی', 'legal_aid', '{"national","sindh"}', null, null, null, 'https://www.legalaidsociety.org.pk/', 'Working hours', 'کام کے اوقات', 'Free legal representation and advice, with particular strength in criminal cases and access to justice for women and detainees. Based in Karachi with national programmes.', 'مفت قانونی نمائندگی اور مشورہ، خاص طور پر فوجداری مقدمات اور خواتین و زیرِ حراست افراد کے لیے انصاف تک رسائی میں۔ کراچی میں قائم، قومی سطح پر پروگرام۔', null, '{"family_law","physical","sexual","domestic","economic"}', 2, 'unconfirmed', 'Confirm the current intake phone number and referral process.', true),
  ('rozan', 'Rozan Counselling Helpline', 'روزن کاؤنسلنگ ہیلپ لائن', 'counselling', '{"national","ict"}', '0304-111-1741', null, null, 'https://rozan.org/', 'Monday to Friday, working hours', 'پیر تا جمعہ، کام کے اوقات', 'Confidential psychological counselling for women and children affected by violence and abuse. Useful when you need to think through options before taking any formal step.', 'تشدد اور زیادتی سے متاثرہ خواتین اور بچوں کے لیے خفیہ نفسیاتی کاؤنسلنگ۔ جب آپ کوئی رسمی قدم اٹھانے سے پہلے اپنے راستے سوچنا چاہتی ہوں تو مفید ہے۔', '{"woman","child"}', '{"domestic","sexual","physical","child"}', 2, 'unconfirmed', 'Confirm the helpline number and current operating hours.', true),
  ('sahil', 'Sahil', 'ساحل', 'child', '{"national"}', null, null, null, 'https://sahil.org/', 'Working hours', 'کام کے اوقات', 'Specialises in child sexual abuse: free legal aid, counselling for children and families, and support through the investigation and trial.', 'بچوں کے جنسی استحصال میں مہارت رکھتی ہے: مفت قانونی مدد، بچوں اور خاندانوں کے لیے کاؤنسلنگ، اور تفتیش و مقدمے میں معاونت۔', '{"child"}', '{"child","sexual"}', 2, 'unconfirmed', 'Confirm the current toll-free helpline number.', true),
  ('aurat_foundation', 'Aurat Foundation', 'عورت فاؤنڈیشن', 'ngo', '{"national"}', null, null, null, 'https://www.af.org.pk/', 'Working hours', 'کام کے اوقات', 'Women''s rights organisation with offices across all four provinces. Provides referral to legal aid, crisis support and advocacy, and can help you find a local service where none is listed here.', 'خواتین کے حقوق کی تنظیم جس کے دفاتر چاروں صوبوں میں ہیں۔ قانونی مدد، بحرانی معاونت اور وکالت کے لیے رہنمائی فراہم کرتی ہے، اور مقامی خدمات تلاش کرنے میں مدد کر سکتی ہے۔', '{"woman"}', '{"domestic","economic","family_law","harmful_practice","other"}', 3, 'unconfirmed', 'Confirm provincial office contact numbers.', true),
  ('shirkat_gah', 'Shirkat Gah', 'شرکت گاہ', 'ngo', '{"national"}', null, null, null, 'https://shirkatgah.org/', 'Working hours', 'کام کے اوقات', 'Women''s resource centre working on legal awareness, reproductive rights and access to justice, with a long record on family law and inheritance cases.', 'خواتین کا وسائل مرکز جو قانونی آگاہی، تولیدی حقوق اور انصاف تک رسائی پر کام کرتا ہے، اور عائلی قوانین و وراثت کے مقدمات میں دیرینہ تجربہ رکھتا ہے۔', '{"woman"}', '{"family_law","economic","domestic"}', 3, 'unconfirmed', 'Confirm office contact numbers for Lahore and Karachi.', true),
  ('pcsw_1043', 'Punjab Women''s Helpline (PCSW)', 'پنجاب ویمن ہیلپ لائن', 'government', '{"punjab"}', '1043', null, null, 'https://pcsw.punjab.gov.pk/', '24/7', 'ہر وقت', 'Toll-free helpline staffed entirely by women, with legal advisors and psychosocial counsellors. They can also arrange shelter and connect you to a Violence Against Women Centre.', 'مکمل طور پر خواتین عملے پر مشتمل مفت ہیلپ لائن، جس میں قانونی مشیر اور نفسیاتی کاؤنسلر شامل ہیں۔ وہ پناہ گاہ کا انتظام اور وی اے ڈبلیو سینٹر سے رابطہ بھی کروا سکتی ہیں۔', '{"woman"}', '{"domestic","physical","sexual","workplace","family_law","economic"}', 1, 'confirmed', null, true),
  ('vawc_punjab', 'Violence Against Women Centre (VAWC)', 'وائلنس اگینسٹ ویمن سینٹر', 'government', '{"punjab"}', null, null, null, null, '24/7', 'ہر وقت', 'One-stop centres where FIR registration, medical examination, forensics, prosecution, counselling and short-stay shelter all happen in one building, so you do not have to repeat your account at four separate offices. Reach one through 1043.', 'ایک ہی چھت کے نیچے مرکز جہاں ایف آئی آر، طبی معائنہ، فرانزک، استغاثہ، کاؤنسلنگ اور عارضی پناہ سب ایک جگہ دستیاب ہیں، تاکہ آپ کو اپنی بات چار مختلف دفاتر میں دہرانی نہ پڑے۔ 1043 کے ذریعے رابطہ کریں۔', '{"woman"}', '{"domestic","physical","sexual"}', 1, 'confirmed', 'Confirm which districts currently have an operational VAWC, and add direct numbers.', true),
  ('cpwb_punjab', 'Child Protection & Welfare Bureau, Punjab', 'چائلڈ پروٹیکشن اینڈ ویلفیئر بیورو، پنجاب', 'child', '{"punjab"}', '1121', null, null, null, '24/7', 'ہر وقت', 'Provincial body for children at risk of abuse, neglect, child labour or child marriage. Can take a child into protective custody.', 'زیادتی، نظراندازی، مشقت یا کم عمری کی شادی کے خطرے سے دوچار بچوں کے لیے صوبائی ادارہ۔ بچے کو تحفظ میں لے سکتا ہے۔', '{"child"}', '{"child","harmful_practice"}', 2, 'unconfirmed', 'Confirm 1121 is still the live short code.', true),
  ('aghs', 'AGHS Legal Aid Cell', 'اے جی ایچ ایس لیگل ایڈ سیل', 'legal_aid', '{"punjab"}', '0800-00123', null, null, null, 'Working hours', 'کام کے اوقات', 'Pakistan''s oldest free legal aid organisation for women, based in Lahore. Handles family court cases, protection orders and criminal complaints, and runs the Dastak shelter.', 'خواتین کے لیے پاکستان کی قدیم ترین مفت قانونی امداد کی تنظیم، لاہور میں قائم۔ فیملی کورٹ کے مقدمات، تحفظ کے احکامات اور فوجداری شکایات دیکھتی ہے، اور دستک شیلٹر چلاتی ہے۔', '{"woman"}', '{"family_law","domestic","sexual","economic"}', 2, 'unconfirmed', 'The number 0800-00123 was inherited from the original prototype and has not been verified. Confirm with AGHS directly before this is shown to users.', true),
  ('dastak', 'Dastak Charitable Trust (shelter)', 'دستک چیریٹیبل ٹرسٹ (پناہ گاہ)', 'shelter', '{"punjab"}', null, null, null, null, '24/7', 'ہر وقت', 'Independent shelter in Lahore for women fleeing violence or forced marriage, with legal support attached through AGHS. An alternative for women who do not want to enter a government Dar-ul-Aman.', 'لاہور میں تشدد یا جبری شادی سے بھاگنے والی خواتین کے لیے خودمختار پناہ گاہ، جس کے ساتھ اے جی ایچ ایس کی قانونی معاونت منسلک ہے۔ ان خواتین کے لیے متبادل جو سرکاری دارالامان نہیں جانا چاہتیں۔', '{"woman","child"}', '{"domestic","harmful_practice","physical"}', 2, 'unconfirmed', 'Confirm intake number and whether direct approach is accepted.', true),
  ('bedari', 'Bedari', 'بیداری', 'ngo', '{"punjab"}', '0300-5251717', null, null, 'https://bedari.org.pk/', 'Monday to Friday, working hours', 'پیر تا جمعہ، کام کے اوقات', 'Legal aid, counselling and shelter referral for women and children, with a focus on rural Punjab where formal services are thin.', 'خواتین اور بچوں کے لیے قانونی مدد، کاؤنسلنگ اور پناہ گاہ تک رہنمائی، خاص طور پر دیہی پنجاب میں جہاں رسمی خدمات کم ہیں۔', '{"woman","child"}', '{"domestic","child","harmful_practice","family_law"}', 3, 'unconfirmed', 'Confirm the mobile helpline number is still in service.', true),
  ('war_lahore', 'War Against Rape (WAR) — Lahore', 'وار اگینسٹ ریپ — لاہور', 'ngo', '{"punjab"}', null, null, null, 'https://war.org.pk/', 'Working hours', 'کام کے اوقات', 'Specialist support for survivors of sexual assault: accompaniment to the medico-legal examination, free legal representation, and counselling.', 'جنسی تشدد سے بچ جانے والوں کے لیے خصوصی معاونت: میڈیکو لیگل معائنے میں ہمراہی، مفت قانونی نمائندگی، اور کاؤنسلنگ۔', null, '{"sexual"}', 2, 'unconfirmed', 'Confirm the Lahore office phone number.', true),
  ('sindh_women_helpline', 'Sindh Women''s Helpline', 'سندھ ویمن ہیلپ لائن', 'government', '{"sindh"}', '1094', null, null, null, 'Working hours', 'کام کے اوقات', 'Women Development Department helpline for Sindh, providing guidance, complaint registration and referral.', 'سندھ کے محکمہ ترقیِ نسواں کی ہیلپ لائن، جو رہنمائی، شکایت کے اندراج اور رجوع کی سہولت دیتی ہے۔', '{"woman"}', '{"domestic","physical","workplace","family_law"}', 1, 'unconfirmed', '1094 was inherited from the original prototype. Confirm it is live and staffed, and establish its actual hours.', true),
  ('war_karachi', 'War Against Rape (WAR) — Karachi', 'وار اگینسٹ ریپ — کراچی', 'ngo', '{"sindh"}', null, null, null, 'https://war.org.pk/', 'Working hours', 'کام کے اوقات', 'Karachi-based specialist service for survivors of sexual assault: medico-legal accompaniment, free legal aid and psychological support.', 'کراچی میں جنسی تشدد سے بچ جانے والوں کے لیے خصوصی ادارہ: میڈیکو لیگل معائنے میں ہمراہی، مفت قانونی مدد اور نفسیاتی معاونت۔', null, '{"sexual"}', 2, 'unconfirmed', 'Confirm the Karachi office phone number.', true),
  ('scsw', 'Sindh Commission on the Status of Women', 'سندھ کمیشن برائے حیثیتِ نسواں', 'government', '{"sindh"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Provincial oversight body for women''s rights in Sindh. Receives complaints where a government department has failed to act.', 'سندھ میں خواتین کے حقوق کا صوبائی نگران ادارہ۔ ان شکایات کو دیکھتا ہے جہاں کسی سرکاری محکمے نے کارروائی نہ کی ہو۔', '{"woman"}', '{"other","workplace"}', 4, 'unconfirmed', 'Confirm contact details and complaint intake route.', true),
  ('kpcsw', 'KP Commission on the Status of Women', 'خیبر پختونخوا کمیشن برائے حیثیتِ نسواں', 'government', '{"kp"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Provincial commission overseeing women''s rights in Khyber Pakhtunkhwa, and the body to approach where a department has refused to act on a complaint.', 'خیبر پختونخوا میں خواتین کے حقوق کی نگرانی کرنے والا صوبائی کمیشن، اور وہ ادارہ جس سے رجوع کیا جائے جب کوئی محکمہ شکایت پر کارروائی سے انکار کرے۔', '{"woman"}', '{"other","workplace","domestic"}', 3, 'unconfirmed', 'Confirm contact number and complaint intake route.', true),
  ('da_hawwa_lur', 'Da Hawwa Lur (shelter, Peshawar)', 'دا حوا لور (پناہ گاہ، پشاور)', 'shelter', '{"kp"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Peshawar-based organisation providing shelter, legal aid and counselling for women facing violence in Khyber Pakhtunkhwa.', 'پشاور میں قائم تنظیم جو خیبر پختونخوا میں تشدد کا سامنا کرنے والی خواتین کو پناہ، قانونی مدد اور کاؤنسلنگ فراہم کرتی ہے۔', '{"woman","child"}', '{"domestic","harmful_practice","physical"}', 2, 'unconfirmed', 'Confirm the organisation is still operating and get its intake number.', true),
  ('blue_veins', 'Blue Veins', 'بلیو وینز', 'ngo', '{"kp"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Peshawar-based rights organisation, one of the few in Khyber Pakhtunkhwa working directly with transgender people as well as women, on violence, healthcare access and legal recognition.', 'پشاور میں قائم حقوق کی تنظیم، خیبر پختونخوا میں ان چند اداروں میں سے ایک جو خواتین کے ساتھ ساتھ ٹرانسجینڈر افراد کے ساتھ تشدد، صحت کی سہولیات اور قانونی شناخت پر براہِ راست کام کرتی ہے۔', '{"woman","transgender"}', '{"physical","sexual","other"}', 3, 'unconfirmed', 'Confirm contact details and current programme areas.', true),
  ('bcsw', 'Balochistan Commission on the Status of Women', 'بلوچستان کمیشن برائے حیثیتِ نسواں', 'government', '{"balochistan"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'Provincial commission for women''s rights in Balochistan. Formal services in the province are limited, so the national 1099 helpline is often the faster route.', 'بلوچستان میں خواتین کے حقوق کا صوبائی کمیشن۔ صوبے میں رسمی خدمات محدود ہیں، اس لیے قومی ہیلپ لائن 1099 اکثر تیز راستہ ہوتا ہے۔', '{"woman"}', '{"other","domestic","workplace"}', 3, 'unconfirmed', 'Confirm contact details and whether complaint intake is operational.', true),
  ('aurat_balochistan', 'Aurat Foundation — Quetta', 'عورت فاؤنڈیشن — کوئٹہ', 'ngo', '{"balochistan"}', null, null, null, 'https://www.af.org.pk/', 'Working hours', 'کام کے اوقات', 'Provincial office providing legal referral and crisis support in Balochistan, where dedicated women''s services are scarce.', 'صوبائی دفتر جو بلوچستان میں قانونی رہنمائی اور بحرانی معاونت فراہم کرتا ہے، جہاں خواتین کے لیے مخصوص خدمات کم ہیں۔', '{"woman"}', '{"domestic","family_law","harmful_practice","other"}', 3, 'unconfirmed', 'Confirm the Quetta office contact number.', true),
  ('gb_social_welfare', 'Gilgit-Baltistan Social Welfare Department', 'گلگت بلتستان محکمہ سماجی بہبود', 'government', '{"gb"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'The district Social Welfare office is the main route to shelter and support in Gilgit-Baltistan, where dedicated women''s helplines are not established. The national 1099 helpline also covers this region.', 'گلگت بلتستان میں پناہ اور معاونت کا بنیادی راستہ ضلعی محکمہ سماجی بہبود ہے، جہاں خواتین کے لیے مخصوص ہیلپ لائنیں قائم نہیں۔ قومی ہیلپ لائن 1099 بھی اس علاقے کو کور کرتی ہے۔', null, '{"domestic","child","other"}', 3, 'unconfirmed', 'Establish which district offices handle violence cases and whether any shelter capacity exists in GB.', true),
  ('ajk_social_welfare', 'AJK Social Welfare & Women Development Department', 'آزاد کشمیر محکمہ سماجی بہبود و ترقیِ نسواں', 'government', '{"ajk"}', null, null, null, null, 'Working hours', 'کام کے اوقات', 'The departmental route to shelter, counselling and legal referral in Azad Jammu & Kashmir. AJK has its own legislature, so some federal statutes apply only once adopted locally. The national 1099 helpline also covers this region.', 'آزاد جموں و کشمیر میں پناہ، کاؤنسلنگ اور قانونی رہنمائی کا محکمانہ راستہ۔ آزاد کشمیر کی اپنی اسمبلی ہے، اس لیے کچھ وفاقی قوانین مقامی سطح پر منظوری کے بعد ہی لاگو ہوتے ہیں۔ قومی ہیلپ لائن 1099 بھی اس علاقے کو کور کرتی ہے۔', null, '{"domestic","child","family_law","other"}', 3, 'unconfirmed', 'Confirm departmental contacts, and establish which federal statutes AJK has adopted.', true)
on conflict (id) do update set
  name = excluded.name,
  name_ur = excluded.name_ur,
  type = excluded.type,
  scope = excluded.scope,
  phone = excluded.phone,
  whatsapp = excluded.whatsapp,
  email = excluded.email,
  website = excluded.website,
  hours = excluded.hours,
  hours_ur = excluded.hours_ur,
  description = excluded.description,
  description_ur = excluded.description_ur,
  serves = excluded.serves,
  handles = excluded.handles,
  priority = excluded.priority,
  published = excluded.published;

commit;
